[manifest]
version = "1.0.0"
dump_lua = true
priority = -1
# patch for ltm packs and regular packs
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'after'
pattern = '''
booster_obj = self.config.center
'''
payload = '''
if self.config.center and self.config.center.key ~= 'packgodfunnymoments' then
    self.ability.extra = self.ability.extra + G.GAME.punch_regular_choices
end
'''